[package]
name = "alpaca"
version = "0.1.0"
authors = ["Alex Egger <alex.egger96@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
spin = "0.5"

[dependencies.lazy_static]
version = "1.4"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
